//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWord_Database
{
    using ConsoleAppWord_Sort;
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WORDS
    {
        public int ID { get; set; }
        public Nullable<int> WORD_LENGTH { get; set; }
        public string WORD { get; set; }

        public override string ToString()
        {
            return StringSort.Get_SortedString(WORD);
        }
    }
}
