//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdevPersoneleGorevAta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;User ID=sa;password=123;Initial Catalog=Northwind;Pooling=true")]
        public string Connection_NorthWind {
            get {
                return ((string)(this["Connection_NorthWind"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select e.EmployeeID,e.FirstName, e.LastName, e.Title, e.BirthDate, e.Country,e.Hi" +
            "reDate,e.Address, e.Notes, e.HomePhone from Employees e")]
        public string Command_SelectEmployee {
            get {
                return ((string)(this["Command_SelectEmployee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into Tasks(TaskName,TaskDescription,TaskDateTime) Values(@TaskName,@TaskDe" +
            "scription,@TaskDateTime) Select @@IDENTITY")]
        public string Command_InsertTask {
            get {
                return ((string)(this["Command_InsertTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Update Tasks Set TaskName = @TaskName, TaskDescription = @TaskDescription,TaskDat" +
            "eTime=@TaskDateTime Where TaskId=")]
        public string Command_UpdateTask {
            get {
                return ((string)(this["Command_UpdateTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into EmployeeTasks(EmployeeTasks_EmployeeId,EmployeeTasks_TaskId) Values(@" +
            "EmployeeTasks_EmployeeId,@EmployeeTasks_TaskId)")]
        public string Command_InsertEmployeeTask {
            get {
                return ((string)(this["Command_InsertEmployeeTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select t.* from Tasks t where TaskId in (select EmployeeTasks_TaskId from Employe" +
            "eTasks where EmployeeTasks_Visible=1 And EmployeeTasks_EmployeeId=\r\n\r\n")]
        public string Command_SelectEmployeeTask {
            get {
                return ((string)(this["Command_SelectEmployeeTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from Tasks where Tasks_Visible=1\r\n\r\n")]
        public string Command_SelectTask {
            get {
                return ((string)(this["Command_SelectTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Update EmployeeTasks  Set EmployeeTasks_Visible = 0 Where EmployeeTasks_TaskId=")]
        public string Command_DeleteTask {
            get {
                return ((string)(this["Command_DeleteTask"]));
            }
        }
    }
}
